
export enum PropertyPostTag {
  Apartment = 'شقة',
  Building = 'عمارة',
  Land = 'أرض',
  Villa = 'فيلا',
  Duplex = 'دوبلكس',
  Studio = 'استوديو',
  House = 'بيت',
  Roof = 'روف',
  Shop = 'محل تجاري',
  Office = 'مكتب',
  Showroom = 'معرض',
  Warehouse = 'مخزن',
  Farm = 'مزرعة',
  Chalet = 'شاليه',
  Resort = 'منتجع',
  Factory = 'مصنع',
  Storage = 'مستودع',
  LaborCamp = 'سكن عمال',
  Garage = 'كراج',
  Tower = 'برج',
  Hotel = 'فندق',
}