export enum ServiceProviderType {
  ELECTRICIAN = 'كهربائي',
  PLUMBER = 'سباك',
  PAINTER = 'دهان',
  CARPENTER = 'نجار',
  INTERIOR_DESIGNER = 'مصمم ديكور',
  CLEANING_SERVICE = 'خدمات تنظيف',
  MOVING_SERVICE = 'خدمات نقل عفش',
  HVAC_TECHNICIAN = 'تبريد وتكييف',
  GLASS_INSTALLER = 'تركيب زجاج',
  ALUMINUM_WORK = 'أعمال ألومنيوم',
  SECURITY_SYSTEMS = 'أنظمة أمان ومراقبة',
  MAINTENANCE = 'صيانة عامة',
  SATELLITE_INSTALLER = 'تركيب دش وأقمار صناعية',
  INTERNET_TECHNICIAN = 'فني إنترنت واتصالات',
  FLOORING = 'تركيب أرضيات',
  CURTAINS_INSTALLER = 'تركيب ستائر',
  ROOFING = 'عزل وأسقف',
  GARDENING = 'تنسيق حدائق',
  WELDING = 'لحام وحدادة',
  DOORS_WINDOWS = 'تركيب أبواب ونوافذ',
}