
export const SyrianGovernorates = [
    {
      name: 'دمشق',
      regions: [
        { name: 'المزة', default_meter_price: 1000 },
        { name: 'المالكي', default_meter_price: 1000 },
        { name: 'برزة', default_meter_price: 1000 },
        { name: 'ركن الدين', default_meter_price: 1000 },
        { name: 'الصالحية', default_meter_price: 1000 },
        { name: 'الزاهرة', default_meter_price: 1000 },
        { name: 'مشروع دمر', default_meter_price: 1000 },
        { name: 'القدم', default_meter_price: 1000 },
        { name: 'كفرسوسة', default_meter_price: 1000 },
        { name: 'باب توما', default_meter_price: 1000 },
        { name: 'العمارة', default_meter_price: 1000 },
        { name: 'الميدان', default_meter_price: 1000 },
        { name: 'الشاغور', default_meter_price: 1000 },
        { name: 'جوبر', default_meter_price: 1000 },
        { name: 'القابون', default_meter_price: 1000 },
        { name: 'المهاجرين', default_meter_price: 1000 },
      ],
    },
    {
      name: 'ريف دمشق',
      regions: [
        { name: 'جرمانا', default_meter_price: 1000 },
        { name: 'صحنايا', default_meter_price: 1000 },
        { name: 'قدسيا', default_meter_price: 1000 },
        { name: 'دوما', default_meter_price: 1000 },
        { name: 'حرستا', default_meter_price: 1000 },
        { name: 'التل', default_meter_price: 1000 },
        { name: 'معضمية الشام', default_meter_price: 1000 },
        { name: 'يبرود', default_meter_price: 1000 },
        { name: 'الكسوة', default_meter_price: 1000 },
        { name: 'الزبداني', default_meter_price: 1000 },
        { name: 'سقبا', default_meter_price: 1000 },
        { name: 'داريا', default_meter_price: 1000 },
        { name: 'النبك', default_meter_price: 1000 },
        { name: 'عين ترما', default_meter_price: 1000 },
      ],
    },
    {
      name: 'حلب',
      regions: [
        { name: 'الفرقان', default_meter_price: 1000 },
        { name: 'الأعظمية', default_meter_price: 1000 },
        { name: 'السليمانية', default_meter_price: 1000 },
        { name: 'الجميلية', default_meter_price: 1000 },
        { name: 'المشارقة', default_meter_price: 1000 },
        { name: 'الشيخ مقصود', default_meter_price: 1000 },
        { name: 'الحمدانية', default_meter_price: 1000 },
        { name: 'صلاح الدين', default_meter_price: 1000 },
        { name: 'الأنصاري', default_meter_price: 1000 },
        { name: 'الميدان', default_meter_price: 1000 },
        { name: 'الهلك', default_meter_price: 1000 },
        { name: 'باب النيرب', default_meter_price: 1000 },
        { name: 'الراموسة', default_meter_price: 1000 },
      ],
    },
    {
      name: 'حمص',
      regions: [
        { name: 'الوعر', default_meter_price: 1000 },
        { name: 'بابا عمرو', default_meter_price: 1000 },
        { name: 'الخالدية', default_meter_price: 1000 },
        { name: 'الإنشاءات', default_meter_price: 1000 },
        { name: 'عكرمة', default_meter_price: 1000 },
        { name: 'حي الزهراء', default_meter_price: 1000 },
        { name: 'كرم الشامي', default_meter_price: 1000 },
        { name: 'باب تدمر', default_meter_price: 1000 },
        { name: 'دير بعلبة', default_meter_price: 1000 },
        { name: 'الحميدية', default_meter_price: 1000 },
      ],
    },
    {
      name: 'حماة',
      regions: [
        { name: 'القصور', default_meter_price: 1000 },
        { name: 'العمري', default_meter_price: 1000 },
        { name: 'الضاحية', default_meter_price: 1000 },
        { name: 'الجلاء', default_meter_price: 1000 },
        { name: 'جنوب الملعب', default_meter_price: 1000 },
        { name: 'المدينة', default_meter_price: 1000 },
        { name: 'الطريق الحربي', default_meter_price: 1000 },
        { name: 'الصابونية', default_meter_price: 1000 },
      ],
    },
    {
      name: 'اللاذقية',
      regions: [
        { name: 'الصليبة', default_meter_price: 1000 },
        { name: 'المشروع العاشر', default_meter_price: 1000 },
        { name: 'الرمل الجنوبي', default_meter_price: 1000 },
        { name: 'رأس شمرا', default_meter_price: 1000 },
        { name: 'الدعتور', default_meter_price: 1000 },
        { name: 'الشيخ ضاهر', default_meter_price: 1000 },
        { name: 'حي الزقزقانية', default_meter_price: 1000 },
      ],
    },
    {
      name: 'طرطوس',
      regions: [
        { name: 'الكرامة', default_meter_price: 1000 },
        { name: 'الدوير', default_meter_price: 1000 },
        { name: 'القدموس', default_meter_price: 1000 },
        { name: 'بانياس', default_meter_price: 1000 },
        { name: 'صافيتا', default_meter_price: 1000 },
        { name: 'دريكيش', default_meter_price: 1000 },
        { name: 'الشيخ بدر', default_meter_price: 1000 },
        { name: 'مشتى الحلو', default_meter_price: 1000 },
      ],
    },
    {
      name: 'إدلب',
      regions: [
        { name: 'معرة النعمان', default_meter_price: 1000 },
        { name: 'خان شيخون', default_meter_price: 1000 },
        { name: 'أريحا', default_meter_price: 1000 },
        { name: 'بنش', default_meter_price: 1000 },
        { name: 'سرمين', default_meter_price: 1000 },
        { name: 'كفرنبل', default_meter_price: 1000 },
        { name: 'سراقب', default_meter_price: 1000 },
      ],
    },
    {
      name: 'الرقة',
      regions: [
        { name: 'الطبقة', default_meter_price: 1000 },
        { name: 'المنصورة', default_meter_price: 1000 },
        { name: 'معدان', default_meter_price: 1000 },
      ],
    },
    {
      name: 'دير الزور',
      regions: [
        { name: 'الميادين', default_meter_price: 1000 },
        { name: 'البوكمال', default_meter_price: 1000 },
        { name: 'موحسن', default_meter_price: 1000 },
        { name: 'القورية', default_meter_price: 1000 },
        { name: 'العشارة', default_meter_price: 1000 },
      ],
    },
    {
      name: 'الحسكة',
      regions: [
        { name: 'القامشلي', default_meter_price: 1000 },
        { name: 'رأس العين', default_meter_price: 1000 },
        { name: 'عامودا', default_meter_price: 1000 },
        { name: 'المالكية', default_meter_price: 1000 },
        { name: 'تل تمر', default_meter_price: 1000 },
      ],
    },
    {
      name: 'درعا',
      regions: [
        { name: 'نوى', default_meter_price: 1000 },
        { name: 'طفس', default_meter_price: 1000 },
        { name: 'ازرع', default_meter_price: 1000 },
        { name: 'بصرى الشام', default_meter_price: 1000 },
        { name: 'جاسم', default_meter_price: 1000 },
        { name: 'الشيخ مسكين', default_meter_price: 1000 },
        { name: 'الصنمين', default_meter_price: 1000 },
      ],
    },
    {
      name: 'السويداء',
      regions: [
        { name: 'شهبا', default_meter_price: 1000 },
        { name: 'صلخد', default_meter_price: 1000 },
        { name: 'القريا', default_meter_price: 1000 },
        { name: 'عتيل', default_meter_price: 1000 },
        { name: 'قنوات', default_meter_price: 1000 },
      ],
    },
    {
      name: 'القنيطرة',
      regions: [
        { name: 'خان أرنبة', default_meter_price: 1000 },
        { name: 'جباتا الخشب', default_meter_price: 1000 },
        { name: 'حضر', default_meter_price: 1000 },
        { name: 'الرفيد', default_meter_price: 1000 },
      ],
    },
  ];